export const CAMERA = {
  FOV: 38,
  NEAR: 0.1,
  FAR: 200,
  POSITION: { x: 0, y: 4.5, z: 9.5 },
  LOOK_AT: { x: 0, y: 1.2, z: -8 },
};

export const CAMERA_RELOAD_FOCUS = {
  POSITION_Y: 2.9,
  POSITION_Z: 3.8,
  X_FOLLOW: 0.35,
  LOOK_AT_Y: 1.3,
  BLEND_SPEED: 5,
};

export const ARENA = {
  WIDTH: 12,
  PLAYER_BOUND_X: 5,
  DEPTH: 60,
  ENEMY_SPAWN_Z: -50,
  BULLET_DESPAWN_Z: -60,
};

export const FOG = {
  COLOR: 0x07060d,
  DENSITY: 0.05,
};

export const BACKGROUND_COLOR = 0x030308;

export const GRID = {
  SIZE: 80,
  DIVISIONS: 40,
  COLOR_MAIN: 0x201a38,
  COLOR_SECONDARY: 0x120f22,
  EMISSIVE_COLOR: 0x4a2fb8,
};

export const LIGHTING = {
  AMBIENT_COLOR: 0x1c1730,
  AMBIENT_INTENSITY: 0.38,
  DIRECTIONAL_COLOR: 0x8a72e0,
  DIRECTIONAL_INTENSITY: 0.7,
  DIRECTIONAL_POSITION: { x: 3, y: 10, z: 5 },
  RIM_COLOR: 0xff3b6e,
  RIM_INTENSITY: 0.9,
  RIM_POSITION: { x: -5, y: 3, z: -10 },
};

export const PLAYER = {
  WIDTH: 1.6,
  HEIGHT: 2.2,
  SPAWN_Z: 0,
  MOVE_SMOOTHING: 12,
  MAX_HP: 5,
  CONTACT_DAMAGE: 1,
  INVULNERABILITY_DURATION: 0.8,
  RUN_SPEED_THRESHOLD: 0.6,
  CROUCH_RETURN_DURATION: 0.35,
  RECOIL_DURATION: 0.08,
  RECOIL_JITTER_AMOUNT: 0.04,
  RECOIL_SCALE_PUNCH: 0.06,
  SHOOT_POSE_DURATION: 0.12,
};

export const COVER = {
  Z_OFFSET: -1.3,
  WIDTH: 13,
  HEIGHT: 0.75,
  DEPTH: 0.6,
  SEGMENT_WIDTH: 2.4,
};

export const BULLET = {
  POOL_SIZE: 300,
  BURST_INTERVAL: 0.09,
  RADIUS: 0.08,
  LENGTH: 0.4,
  SPAWN_HEIGHT: 1.3,
};

export const BULLET_LIMITS = {
  MAX_BULLETS_PER_SHOT: 3,
  MAX_FIRE_RATE: 6,
  MAX_DAMAGE: 4,
  MAX_BULLET_SPEED: 36,
  MAX_PIERCE: 3,
  MAX_POISON_STACKS: 5,
  MAX_MAGAZINE_SIZE: 14,
};

export const ENEMY = {
  POOL_SIZE: 90,
  WIDTH: 1.4,
  HEIGHT: 1.9,
  SPEED: 6.2,
  SPEED_VARIANCE: 0.18,
  WOBBLE_AMPLITUDE_MIN: 0.15,
  WOBBLE_AMPLITUDE_MAX: 0.6,
  WOBBLE_FREQUENCY_MIN: 0.5,
  WOBBLE_FREQUENCY_MAX: 1.3,
  HEALTH_BASE: 2,
  HEALTH_GROWTH_PER_SECOND: 0.035,
  HEALTH_CAP: 12,
  COLLISION_RADIUS: 0.6,
  SPAWN_X_SPREAD: 9,
  SPAWN_Z_JITTER: 3,
  BREACH_Z: -1.2,
  HIT_FLASH_DURATION: 0.12,
  HIT_FLASH_SCALE_BOOST: 0.35,
};

export const STAGE = {
  BASE_ENEMY_COUNT: 6,
  ENEMY_COUNT_INCREMENT: 5,
  BASE_SPAWN_INTERVAL: 3.4,
  SPAWN_INTERVAL_DECAY: 0.18,
  MIN_SPAWN_INTERVAL: 1,
  BASE_SPAWN_COUNT: 1,
  MAX_SPAWN_COUNT: 3,
  SPAWN_COUNT_STAGE_STEP: 2,
};

export const CRATE = {
  POOL_SIZE: 8,
  WIDTH: 1.7,
  HEIGHT: 1.05,
  DEPTH: 1.5,
  STRAP_THICKNESS: 0.1,
  TRIM_THICKNESS: 0.06,
  SPEED: 3.4,
  SPAWN_INTERVAL: 38,
  PAIR_HALF_GAP: 2.6,
  PAIR_CENTER_SPREAD: 1.5,
  SPAWN_Z_JITTER: 0.4,
  COLLISION_Z_TOLERANCE: 0.5,
  DESPAWN_Z: 15,
};

export const GEM = {
  POOL_SIZE: 120,
  RADIUS: 0.14,
  COLOR: 0x9b7fff,
  VALUE: 1,
  BASE_HEIGHT: 0.35,
  PICKUP_RADIUS: 0.6,
  MAGNET_SMOOTHING: 6,
  BOB_AMPLITUDE: 0.08,
  BOB_FREQUENCY: 2,
};

export const LEVEL = {
  BASE_EXP: 5,
  EXP_INCREMENT: 3,
};

export const POISON = {
  DAMAGE_PER_TICK_PER_STACK: 0.5,
  TICK_INTERVAL: 0.5,
  TICK_COUNT: 4,
};

export const PARTICLE = {
  POOL_SIZE: 200,
  BURST_COUNT: 8,
  LIFETIME: 0.45,
  SPEED_MIN: 2,
  SPEED_MAX: 5,
  RADIUS: 0.07,
  COLOR: 0xff2d55,
};

export const CAMERA_SHAKE = {
  HIT_MAGNITUDE: 0.18,
  HIT_DURATION: 0.25,
};

export const LIGHTNING = {
  COOLDOWN: 3,
  DAMAGE: 3,
  SEGMENT_COUNT: 6,
  RANGE_Z: -26,
  JITTER_X: 1.6,
  HIT_RADIUS: 0.9,
  VISIBLE_DURATION: 0.15,
  COLOR: 0xbfe0ff,
};

export const WIND_SLASH = {
  COOLDOWN: 2.4,
  DAMAGE: 1.5,
  PROJECTILE_COUNT: 3,
  SPEED: 14,
  SPREAD: 0.9,
  RADIUS: 0.35,
  PIERCE: 20,
  LIFETIME: 2.5,
  POOL_SIZE: 30,
  COLOR: 0x3bffb0,
};

export const GRENADE = {
  COOLDOWN: 4,
  DAMAGE: 2,
  PROJECTILE_COUNT: 3,
  SPEED: 12,
  SPREAD: 1.4,
  FUSE_DURATION: 1.8,
  EXPLOSION_RADIUS: 2.6,
  POOL_SIZE: 12,
  COLOR: 0xffa23b,
};

export const SUBTITLE = {
  MIN_INTERVAL: 14,
  MAX_INTERVAL: 24,
  DISPLAY_DURATION: 4,
  SWAY_INTERVAL: 0.6,
};

export const INPUT = {
  KEYBOARD_SPEED: 8,
};

export const RENDERER = {
  MAX_PIXEL_RATIO: 2,
  ANTIALIAS: true,
};
