export const CAMERA = {
  FOV: 38,
  NEAR: 0.1,
  FAR: 200,
  POSITION: { x: 0, y: 4.5, z: 9.5 },
  LOOK_AT: { x: 0, y: 1.2, z: -8 },
};

export const ARENA = {
  WIDTH: 12,
  PLAYER_BOUND_X: 5,
  DEPTH: 60,
  ENEMY_SPAWN_Z: -50,
  BULLET_DESPAWN_Z: -60,
};

export const FOG = {
  COLOR: 0x0a0a12,
  DENSITY: 0.035,
};

export const BACKGROUND_COLOR = 0x05050a;

export const GRID = {
  SIZE: 80,
  DIVISIONS: 40,
  COLOR_MAIN: 0x2a1f4d,
  COLOR_SECONDARY: 0x1a1430,
  EMISSIVE_COLOR: 0x6a3ffb,
};

export const LIGHTING = {
  AMBIENT_COLOR: 0x2a1f4d,
  AMBIENT_INTENSITY: 0.6,
  DIRECTIONAL_COLOR: 0x9b7fff,
  DIRECTIONAL_INTENSITY: 1.2,
  DIRECTIONAL_POSITION: { x: 3, y: 10, z: 5 },
  RIM_COLOR: 0xff3b6e,
  RIM_INTENSITY: 0.8,
  RIM_POSITION: { x: -5, y: 3, z: -10 },
};

export const PLAYER = {
  WIDTH: 1.6,
  HEIGHT: 2.2,
  SPAWN_Z: 0,
  MOVE_SMOOTHING: 12,
  MAX_HP: 5,
  CONTACT_DAMAGE: 1,
  INVULNERABILITY_DURATION: 0.8,
};

export const BULLET = {
  POOL_SIZE: 300,
  SPEED: 24,
  FIRE_RATE: 1.4,
  BURST_INTERVAL: 0.09,
  VOLLEY_SPREAD: 0.16,
  RADIUS: 0.08,
  LENGTH: 0.4,
  SPAWN_HEIGHT: 1.3,
  COLOR: 0xff3b6e,
  DAMAGE: 1,
};

export const BULLET_LIMITS = {
  MAX_BULLETS_PER_SHOT: 3,
  MAX_FIRE_RATE: 3,
  MAX_DAMAGE: 4,
  MAX_BULLET_SPEED: 36,
  MAX_PIERCE: 3,
  MAX_POISON_STACKS: 5,
};

export const ENEMY = {
  POOL_SIZE: 150,
  WIDTH: 1.4,
  HEIGHT: 1.9,
  SPEED: 6.5,
  SPEED_VARIANCE: 0.18,
  WOBBLE_AMPLITUDE_MIN: 0.15,
  WOBBLE_AMPLITUDE_MAX: 0.6,
  WOBBLE_FREQUENCY_MIN: 0.5,
  WOBBLE_FREQUENCY_MAX: 1.3,
  HEALTH_BASE: 2,
  HEALTH_GROWTH_PER_SECOND: 0.035,
  HEALTH_CAP: 12,
  COLLISION_RADIUS: 0.6,
  SPAWN_INTERVAL: 1.4,
  SPAWN_COUNT_MIN: 2,
  SPAWN_COUNT_MAX: 4,
  SPAWN_X_SPREAD: 9,
  SPAWN_Z_JITTER: 3,
  BREACH_Z: 1.2,
  HIT_FLASH_DURATION: 0.12,
  HIT_FLASH_SCALE_BOOST: 0.35,
};

export const GATE = {
  POOL_SIZE: 12,
  WIDTH: 2.2,
  HEIGHT: 2.6,
  DEPTH: 0.4,
  BAR_THICKNESS: 0.14,
  SPEED: 3.6,
  SPAWN_INTERVAL: 20,
  PAIR_HALF_GAP: 2.6,
  PAIR_CENTER_SPREAD: 1.5,
  SPAWN_Z_JITTER: 0.4,
  COLLISION_Z_TOLERANCE: 0.5,
  DESPAWN_Z: 15,
};

export const GEM = {
  POOL_SIZE: 120,
  RADIUS: 0.14,
  COLOR: 0x9b7fff,
  VALUE: 1,
  BASE_HEIGHT: 0.35,
  PICKUP_RADIUS: 0.6,
  MAGNET_SMOOTHING: 6,
  BOB_AMPLITUDE: 0.08,
  BOB_FREQUENCY: 2,
};

export const LEVEL = {
  BASE_EXP: 5,
  EXP_INCREMENT: 3,
};

export const POISON = {
  DAMAGE_PER_TICK_PER_STACK: 0.5,
  TICK_INTERVAL: 0.5,
  TICK_COUNT: 4,
};

export const INPUT = {
  KEYBOARD_SPEED: 8,
};

export const RENDERER = {
  MAX_PIXEL_RATIO: 2,
  ANTIALIAS: true,
};
